---
- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
    - make
    - gcc

- shell: /opt/libressl/bin/openssl version
  register: libressl_current
  ignore_errors: yes

- name: Download source
  get_url: url=http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-{{ libressl_version }}.tar.gz dest=/tmp/libressl-{{ libressl_version }}.tar.gz
  when: libressl_current.stdout.find('{{ libressl_version }}') == -1

- name: Extract archive
  command: chdir=/tmp/ tar xfz libressl-{{ libressl_version }}.tar.gz creates=/tmp/libressl-{{ libressl_version }}
  when: libressl_current.stdout.find('{{ libressl_version }}') == -1

- name: Make clean
  command: chdir=/tmp/libressl-{{ libressl_version }} make clean
  ignore_errors: yes
  when: libressl_current.stdout.find('{{ libressl_version }}') == -1

- name: Configure
  command: chdir=/tmp/libressl-{{ libressl_version }} ./configure --prefix=/opt/libressl
  when: libressl_current.stdout.find('{{ libressl_version }}') == -1

- name: Make
  command: chdir=/tmp/libressl-{{ libressl_version }} make
  when: libressl_current.stdout.find('{{ libressl_version }}') == -1

- name: Install
  command: chdir=/tmp/libressl-{{ libressl_version }} make install
  become: yes
  when: libressl_current.stdout.find('{{ libressl_version }}') == -1